### ISSUE TITLE
Return type of `atomic_symbol` changed

### ISSUE THREAD

**Issue by rashidrafeek** [JuliaMolSim/AtomsBase.jl#134]
In the 0.5 update, it seems that `atomic_symbol` now returns a `ChemicalSpecies` object and not a `Symbol`.
```julia
using Unitful, AtomsBase
box = ([1, 0, 0]u"m", [0, 1, 0]u"m", [0, 0, 1]u"m")
pbcs = (true, true, false)
atoms = Atom[ChemicalSpecies(:C; atom_name=:MyC) => [0.25, 0.25, 0.25]u"m",
               :C12 => [0.75, 0.75, 0.75]u"m"]
system = FastSystem(atoms, box, pbcs)

typeof(atomic_symbol(system, 1))
```
returns `ChemicalSpecies`. Was this intentional? I was thinking that the `atomic_symbol` is supposed to return a `Symbol`, although the [interface docs](https://juliamolsim.github.io/AtomsBase.jl/stable/apireference/#AtomsBase.atomic_symbol) is also not clear about this. Currently there is a `species` function which returns a ChemicalSpecies object. So if this was intentional, these two functions seems to have the same functionality. Also, It might be helpful to clarify the return type in the interface docs.

**Comment by mfherbst** [comment]
Yes indeed. I also noticed this, but I thought it was intentional. As mentioned by @cortner in https://github.com/JuliaMolSim/AtomsBase.jl/issues/110 the problem with symbols is that they are not `isbits`, but `ChemicalSpecies` is. Perhaps this change was a little too quick as now we have a half-baked thing where some functions `atomic_symbol` return a `ChemicalSpecies` and others like `element_symbol` still return a `Symbol`. (Just to be clear: I can also see reasons for keeping it like this, but we should probably have a discussion about this).

At the very least I agree @rashidrafeek that it should be documented :+1:. Are you able to attend the monthly call next Monday or is this too horrible wrt. your timezone ?

**Comment by rashidrafeek** [comment]
Yeah, it would be great to clarify this in the documentation. Thank you for pointing out the earlier issue—I completely missed it. This seems to be a duplicate and can be addressed there, so I’ll go ahead and close this issue.

I’ll do my best to attend the monthly call on Monday. Will the timings be shared in the Zulip channel? If so, I can plan accordingly. Thanks for the invitation.
