### ISSUE TITLE
Do we really need separate `AbstractParticle` and `AbstractElement` types?

### ISSUE THREAD

**Issue by Gregstrq** [JuliaMolSim/AtomsBase.jl#7]
Right now we have two types describing our particles: `AbstractParticle` and `AbstractElement`.
`AbstractElement` contains the physical information about the element, besides its coordinates and possibly velocities.

At the same time `AbstractParticle` by definition is simply a container which stores `AbstractElement`, vector of coordinates and possibly vector of velocities. Since `AbstractParticle` is simply a container, it does not add anything new in terms of functionality. Moreover, since it may or may not contain velocities, we need to create at least two concrete subtypes: one without velocities and one with them, which again leads to the redundancy in the interface (we need to implement he functions that deal with `AbstractElement` and coordinates for both of these subtypes).

In these regards, Rachel mentioned [this dicsussion](https://github.com/SimonEnsemble/Xtals.jl/issues/102) of the indexing in Xtals package.

So, I propose that we remove `AbstractParticle` type. We can rename `AbstractElement` to `AbstractParticle` although, but it would still correspond to element data without coordinates and velocities. And `getindex` would then simply return a tuple (Element, coordinate) or  (Element, coordinate, velocity).

**Comment by mfherbst** [comment]
To comment on your question Christoph:

> (4) @mfherbst can you explain why you need this in the DFTK setup stage?

In DFTK we have a certain flexibility to setup DFT calculations. The most high-level is `model_LDA(lattice, atoms)` for example and the most low-level `Model(lattice; kwargs...)` where basically you can bootstrap any operator you want including analytic potentials or potentials generated by the atoms. The point now is that the `AbstractSystem` structure/convention in `AtomsBase` sort of supplies both `lattice` and `atoms` and potentially a few other things as well. So at the DFTK level this info somewhere needs to be split apart in a transparent way, such that the full flexibility we have is still kept. At that level we would need multiple dispatch on the "system" object and therefore at least an `AbstractSystem` abstract type would be useful for us.

**Comment by cortner** [comment]
I don't fully see the issue, but also I'm a lot less worried about the AbstractSystem than the AbstractAtom.

**Comment by mfherbst** [comment]
Essentially for compatibility with the interface as we support it now, where the lattice can be just a matrix of numbers or some python object (for ASE compatibility). Especially for the matrix of numbers case it's a bit hackish to define a  `get_lattice` method at all (`get_lattice(a::AbstractMatrix) = a` is a bit abusive in my opinion).

**Comment by rkurchin** [comment]
To be clear though, I don't think there's anything _stopping_ you from defining the interface functions on your own type but not actually subtyping `AbstractSystem`. Some things might not be quite so smooth, but I think it should still work.

And if it wouldn't work, then IMO that would be a problem and it's worth discussing. For example, could what we're after be achieved by some sort of trait instead of actually inserting something into the type hierarchy? I could imagine that other package developers might not always want to make their type a subtype of `AbstractSystem`, for instance, if they've already chosen to subtype `AbstractArray`...

**Comment by cortner** [comment]
> I could imagine that other package developers might not always want to make their type a subtype of AbstractSystem, for instance, if they've already chosen to subtype AbstractArray...

yes, that is precisely the point. It is not the end of the world, we just need to start converting then. But if we worked purely with an interface, then no need!

**Comment by rkurchin** [comment]
I'm going to try gradually removing pieces and only ever commit working versions over at #23, so you can keep an eye out there. So far, I've pushed a version that removes `AbstractElement` but keeps everything else. I'll plan on going all the way to introducing no abstract types so that we can see what that case might look like as well, which I think will help us decide if that's what we want or if some intermediate case is best.

Thanks @cortner for forcing us to think through all this really carefully; this will undoubtedly be better for it, wherever we land!

**Comment by jgreener64** [comment]
I can see both sides but personally I would lean towards keeping `AbstractSystem` for its general use in dispatching, one example being defining plot recipes.

Ironically the use of having something be a subtype of `AbstractArray` points to the future potential of `AbstractSystem`. From the Julia interface docs:

> If a type is defined as a subtype of `AbstractArray`, it inherits a very large set of rich behaviors including iteration and multidimensional indexing built on top of single-element access.

I worry we lock ourselves out of this potential if we don't introduce `AbstractSystem`.

**Comment by cortner** [comment]
I agree that’s another important point - to inherit behaviour. As I said I don’t have a strong view on AbstractSystem. 

That said - one can always “inherit” behaviour via a macro

**Comment by rkurchin** [comment]
@cortner, curious for your thoughts on the current state of #23 as regards the discussion above (that should get merged later today most likely; I need to add a few more tests)

**Comment by cortner** [comment]
see my comments in the review. From here on I think I would need to test this.
