### ISSUE TITLE
Introduce Cell types

### ISSUE THREAD

**Issue by cortner** [JuliaMolSim/AtomsBase.jl#99]
This is a proposal based on the zoom call on 15 / 5 / 2024, that replaces #97 . 

(1) remove `bounding_box` and `boundary_conditions` from the system and replace it with a cell object that encodes the same information. 
(2) Implement a type `Cell` or `ParaCell` that contains fields `cell_vectors` and `pbc` (true / false)
(3) At the same time I would like to replace the `AbstractVector` with `Vector` in order to remove that type instability as well.

It would look something like this: 
```julia
struct FlexibleSystem{D, TPART, TCELL} <: AbstractSystem{D}
    particles::Vector{TPART}
    cell::TCELL
    data::Dict{Symbol, Any}
end

struct ParaCell{D, T}
    cell_vectors::NTuple{D, SVector{3, T}}
    pbc::NTuple{D, Bool}
end
```

I think this will do two things: 
- make the `FlexibleSystem` type stable
- increase flexibility

I'll start on the PR if I get tentative agreement from a few people.

**Comment by rkurchin** [comment]
I don't really have particularly strong feelings about how exactly we do things in the `FastSystem` and `FlexibleSystem` example implementations, but I presume this has a corresponding proposal for how the interface functions change?

I'm presuming based on our conversation earlier:
* get rid of [these lines](https://github.com/JuliaMolSim/AtomsBase.jl/blob/ba4f510898a48f5429e6f955cb3ce2b70bbfefe8/src/interface.jl#L13C1-L15C57) entirely
* change [this](https://github.com/JuliaMolSim/AtomsBase.jl/blob/ba4f510898a48f5429e6f955cb3ce2b70bbfefe8/src/interface.jl#L43) so that it returns a vector of `Bool`s with a length equal to `D`?

**Comment by cortner** [comment]
I would try to stay as close as possible to the current interface. I don't know exactly what changes are needed until I work on this.

**Comment by mfherbst** [comment]
I'm ok with this, provided that we have enough sugar that I don't have to go down to the cell datastructure when I just want to get the cell vectors out of a system. Because that's one thing I really dislike about the packages that abstract away the vectors in a cell structure is that this makes working with them quite inconvenient at times.

**Comment by cortner** [comment]
> I would try to stay as close as possible to the current interface.

**Comment by jgreener64** [comment]
I am okay with this, I don't have strong feelings about how `FastSystem` and `FlexibleSystem` are implemented. As Rachel says it is more about the interface functions.
